config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  resources :categories
  get 'categories/index'

  get 'categories/edit'

  get 'categories/show'

  get 'categories/new'

  get 'home/index'
  
  resources :posts
  
  resources :categories
  
  resources :pages
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/resources', to: 'pages#resources'

   root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
		 
    has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	belongs_to :category
	belongs_to :admin_user
	has_many :post_comments, :dependent => :destroy
	validates :title, :presence => true
	validates_length_of :body, :minimum => 10
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true, length: { in: 2..20}
  validates :email, presence: true
  validates :body, presence: true
 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :all_categories
  helper_method :all_posts
  before_filter :site_search
  
  def all_categories
	@categories = Category.all
  end
  
  def all_posts
	@posts = Post.all.order('created_at desc').limit(4)
  end
  
  def site_search
		@search = Post.ransack(params[:q])
		@posts = @search.result
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
	@category = Category.find(params[:id])
	@title = @category.name
	@posts = @category.posts
  end

 # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base
def create
		@post_comment = PostComment.new(post_comment_params)
		
		if @post_comment.save
			flash[:notice] = 'Comment was successfully created.'
			redirect_to(@post_comment.post)
		else
			flash[:notice] = 'Error creating post_comment : #(@post_comment.errors)'
			redirect_to(@post_comment.post)
		
		end
	end
  private

    def post_comment_params
      params.require(:post_comment).permit(:name, :email, :body, :post_id)
    end
	
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def post_params
      params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
	  
    end
	
	def index
		@search = Post.ransack(params[:q])
		@posts = @search.result
	
		# @posts = Post.all
	end
	
	
	def show
		@post = Post.find(params[:id])
		@user = AdminUser.all
		@post_comment = PostComment.new(:post => @post)
	
	end
	
	def new
	
		@post = Post.new
		@category = Category.all
		
	end
	
	
	def create
		
		@post =  Post.new(post_params)
		
			if @post.save
				redirect_to posts_path, :notice => "your post has been saved"
			
			else
			
				render "new"
				
			
			end
	
	end
	
	def edit
	
		@post = Post.find(params[:id])
	
	end
	
	def update
		
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
				redirect_to posts_path, :notice => "your post has been updated"
			
			else
			
				render "edit"
				
			
		end
		
	end
	
	
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy!
		redirect_to posts_path, :notice => "Your post has been deleted"
	
	end
	
	
	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="post">
<h1>Listing Categories</h1>
<hr>
<ul>
    <% @categories.each do |category| %>
   <li>   <%= link_to category.name,category_path(:id => category.id) %></li>
       
    <% end %>
</ul>
<br>
</div>

app/views/categories/show.html.erb
<h1 style="color:#ffffff"><%= @category.name %></h1>
<hr>

		<% if @posts.each do |post| %>
		<div class="post">
	
			<h2 class="title"><%= link_to post.title, post %></h2><hr>
			<div class="entry"><%= post.body %></div>
			<div class="byline">
								<p class="meta">May 01, 2012 Posted by : <%= post.admin_user.name %></p>
								<p class="links"><%= link_to "Read more", post_path(:id => post.id) %></p>
			</div>
			</div>
		<% end.empty? %>
		<div class="post">
			<p>Sorry, there are no posts in this category.</p>
		</div>
			
		<% end %>
		
			<%= link_to "Back to Categories", categories_path %>
		

app/views/home/index.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<div class="entry"><%= post.body %></div>
		<div class="byline">
							<p class="meta">May 01, 2012 Posted by : <%= post.admin_user.name %></p>
							<p class="links"><%= link_to "Read more", post_path(:id => post.id) %></p>
		</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<div class="flash-message">
						<% flash.each do |key,value| %>
						<p><%= value %></p>
						<% end %>
					</div>

					
					<div style="clear: both;"><%= yield %><!-- Main view -->
					</div>
				</div>
				<!-- end #content -->
				<%= render "partials/sidebar" %>
				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
	<div id="footer">
		<p>&copy; 2013, My Ruby Blog - Sample Project</p>
	</div>
</div>
<!-- end #footer -->

</body>
</html>

app/views/pages/about.html.erb
<div class="post">
	<h1>About Myrubyblog </h1>
	<p>What is Lorem Ipsum?
	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
	<h1>Pages#contact</h1>
	<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
	<h1>Pages#resources</h1>
	<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Ruby Blog</title>
  <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">My Ruby Blog</a></h1>
				
			</div>
			<div id="menu">
				
				<ul>
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Blog", posts_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to "Reources", resources_path %></li>
				</ul>
	
			</div>
		</div>
	</div>
	<!-- end #header -->

app/views/partials/_post_comment.html.erb
<div class="post_comment">
	<i><%= post_comment.name %> says : </i><br/>
	<%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
<div id="sidebar">
					<ul>
						<li>
							<div id="search" >
								<%= search_form_for @search do |f| %>
									<%= f.text_field :title_or_body_contains %>

									<%= f.submit "Search" %>

								<% end %> 
							</div>
							<div style="clear: both;">&nbsp;</div>
						</li>
						
						<li>
							<h2>Categories</h2>
							<ul>
								<% all_categories.each do |cat| %>
									<li><%= link_to cat.name, category_path(:id => cat.id) %></li>
								<% end %>
								
							</ul>
						</li>
						<li>
							<h2>Blogroll</h2>
							<ul>
							<% all_posts.each do |post| %>
									<li><%= link_to post.title, post_path(:id => post.id) %></li>
								<% end %>
								</ul>
						</li>
						
					</ul>
				</div>
				

app/views/post_comments/_form.html.erb
<%= form_for(@post_comment) do |f| %>
  <% if @post_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
      <% @post_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/post_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.name %></td>
        <td><%= post_comment.email %></td>
        <td><%= post_comment.body %></td>
        <td><%= post_comment.post %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(post_comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post comment', new_post_comment_path %>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post_comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post_comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post_comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/posts/index.html.erb
		<% if @posts.each do |post| %>
		<div class="post">
	
			<h2 class="title"><%= link_to post.title, post %></h2><hr>
			<div class="entry"><%= post.body %></div>
			<div class="byline">
								<p class="meta">May 01, 2012 Posted by : <%= post.admin_user.name %></p>
								<p class="links"><%= link_to "Read more", post_path(:id => post.id) %></p>
			</div>
			</div>
		<% end.empty? %>
		<div class="post">
			<p>Sorry, there are no posts in this category.</p>
		</div>
			
		<% end %>
		

app/views/posts/show.html.erb
<div class="post">
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p>Created By : <%= @post.admin_user.name %></p>
<p><%= @post.body %></p>
Category : <%= link_to @post.category.name,category_path(:id => @post.category.id) %>
<p><%= link_to "Back", posts_path %></p>

<h3>Add a comment</h3>
<%= form_for @post_comment do |f| %>
	<%= f.hidden_field :post_id %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :body %><br/>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Post Comment" %>
		
	</p>
<% end %>
<%= render :partial => 'partials/post_comment', :collection => @post.post_comments %>
</div>